Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "= 20181222.0.0"

  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network :private_network, ip: "10.0.0.10"
  config.vm.hostname = "gitlab"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.name = "gitlab"
  end

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = ["cookbooks", "../../cookbooks"]

    chef.json = {
      "gitlab.rb" => File.read('gitlab.rb'),
      "ssh-ring" => {
          "home-dirs" => {
              "gitlab-runner" => "/home/gitlab-runner"
          }
      },
      "deps-p1-build" => {
        "user" => "gitlab-runner"
      },
      "deps-p3-build" => {
        "user" => "gitlab-runner"
      }
    }

    chef.add_recipe "hosts"
    chef.add_recipe "gitlab-omnibus"
    chef.add_recipe "gitlab-runner"
    chef.add_recipe "ssh-ring"
    chef.add_recipe "deps-p1-build"
    chef.add_recipe "deps-p2-build"
    chef.add_recipe "deps-p3-build"
  end
end
