Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "= 20181222.0.0"

  config.vm.network "forwarded_port", guest: 8153, host: 8153
  config.vm.network :private_network, ip: "10.0.0.14"
  config.vm.hostname = "droneio"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.name = "droneio"
  end

  config.vm.synced_folder "../../projects/", "/src/", mount_options: ["dmode=555,fmode=444"]

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = ["cookbooks", "../../cookbooks"]

    chef.json = {
      "ssh-ring" => {
          "home-dirs" => {
              "root" => "/root"
          }
      }
    }

    chef.add_recipe "hosts"
    chef.add_recipe "droneio"
    chef.add_recipe "ssh-ring"
  end
end
