stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - bundle install

build:
  stage: build
  artifacts:
    paths:
      - _site/
  script:
    - make build

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - make deploy
