stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - _site/
  script:
    - rvm use 2.6
    - gem install jekyll bundler
    - bundle install
    - make build

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - make deploy
